# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Chen's Blog
tagline:          'Web Developer HTML5 Canvas dotnet'
description:      'I am Chen, a Web Developer'
url:              http://imzc.me
baseurl:          /

author:
  name:           'Chen Zhang'
  url:            http://imzc.me

paginate:         5

github:
  repo:           https://github.com/zcxp
