# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            I am ZC
tagline:          'Web Developer HTML5 Canvas dotnet'
description:      'I am ZC, and I am a Web Developer'
url:              http://imzc.me
baseurl:          /

author:
  name:           'Chen Zhang'
  url:            https://imzc.me

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/zcxp
